version: '3.4'
services:
  ffmpeg-watch:
    container_name: ffmpeg-watch
    build: .
    restart: always
    environment:
      ENCODER: libx265
      PRESET: veryfast
      CRF: 29
      EXTENSION: mp4
    volumes:
      - './storage:/storage'
      - './watch:/watch'
      - './output:/output'
